# Generated by Django 5.0.7 on 2024-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividaderegistro',
            name='comentarios',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='atividaderegistro',
            name='equipe_adicional',
            field=models.ManyToManyField(blank=True, related_name='atividades_registradas', to='ieb.equipeprojeto'),
        ),
    ]
