# Generated by Django 5.0.6 on 2024-09-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0003_treinados_foco_treinamento_treinados_homens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividaderegistroindicador',
            name='meta_realizada',
        ),
        migrations.AlterField(
            model_name='treinados',
            name='foco_treinamento',
            field=models.CharField(choices=[('implementacao', 'Implementação melhorada/monitoramento/vigilância'), ('ativ_prod', 'Meios de subsistência/cadeia de valor sustentáveis melhorados'), ('governanca', 'Fortalecimento institucional/capacitação organizacional/governança')], default='governanca', max_length=20),
        ),
    ]
