# Generated by Django 5.0.6 on 2024-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0005_remove_leis_nome_remove_leis_tipo_remove_leis_tis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='tis',
        ),
        migrations.AddField(
            model_name='planos',
            name='adotado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planos',
            name='desenvolvimento',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planos',
            name='implementado',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planos',
            name='proposto',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='planos',
            name='total_planos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
