# Generated by Django 5.0.6 on 2024-09-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0006_remove_planos_nome_remove_planos_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='capacitados',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='capacitados',
            name='projeto',
        ),
        migrations.AddField(
            model_name='capacitados',
            name='total_organizacoes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='capacitados',
            name='organizacoes',
            field=models.ManyToManyField(related_name='capacitados', to='ieb.organizacao'),
        ),
    ]
