# Generated by Django 5.0.6 on 2024-09-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0007_organizacao_remove_capacitados_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinados',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='parcerias',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='leis',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='contratos',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='modelos',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='capacitados',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='arearestrito',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='areadireto',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='areageral',
            name='atividade_registro_indicador',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='atividade_registro_indicador',
        ),
        migrations.AddField(
            model_name='areadireto',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='areageral',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='arearestrito',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='capacitados',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='leis',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='modelos',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='parcerias',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='planos',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AddField(
            model_name='treinados',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.AlterField(
            model_name='atividaderegistroequipe',
            name='atividade_registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.DeleteModel(
            name='AtividadeRegistroIndicador',
        ),
    ]
