# Generated by Django 5.0.6 on 2024-09-05 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0009_remove_treinados_nome_remove_treinados_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcerias',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='parcerias',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='parcerias',
            name='tis',
        ),
        migrations.AddField(
            model_name='parcerias',
            name='total_parcerias',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='parcerias',
            name='atividade_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro'),
        ),
        migrations.CreateModel(
            name='Parceria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('atividade_registro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ieb.atividaderegistro')),
            ],
        ),
        migrations.AddField(
            model_name='parcerias',
            name='parcerias',
            field=models.ManyToManyField(related_name='parcerias_atividade', to='ieb.parceria'),
        ),
    ]
