# Generated by Django 5.0.6 on 2024-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0011_remove_parceria_atividade_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PGTA', 'PGTA'), ('Plano de Enfrentamento', 'Plano de Enfrentamento'), ('Plano de Diagnóstico', 'Plano de Diagnóstico')], max_length=255)),
                ('situacao', models.CharField(choices=[('em desenvolvimento', 'Em Desenvolvimento'), ('proposto', 'Proposto'), ('adotado', 'Adotado'), ('implementado', 'Implementado')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='planos',
            name='adotado',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='desenvolvimento',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='implementado',
        ),
        migrations.RemoveField(
            model_name='planos',
            name='proposto',
        ),
        migrations.AlterField(
            model_name='planos',
            name='total_planos',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='planos',
            name='planos',
            field=models.ManyToManyField(related_name='planos', to='ieb.plano'),
        ),
    ]
