# Generated by Django 5.0.6 on 2024-09-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieb', '0012_plano_remove_planos_adotado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_anterior', models.CharField(choices=[('em desenvolvimento', 'Em Desenvolvimento'), ('proposto', 'Proposto'), ('adotado', 'Adotado'), ('implementado', 'Implementado')], max_length=255)),
                ('situacao_nova', models.CharField(choices=[('em desenvolvimento', 'Em Desenvolvimento'), ('proposto', 'Proposto'), ('adotado', 'Adotado'), ('implementado', 'Implementado')], max_length=255)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(max_length=255)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ieb.plano')),
            ],
        ),
    ]
