# Generated by Django 4.2.9 on 2024-09-28 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0013_planohistorico"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividaderegistro",
            name="fotos",
            field=models.ImageField(blank=True, upload_to="fotos/"),
        ),
    ]
