# Generated by Django 4.2.9 on 2024-10-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0014_alter_atividaderegistro_fotos"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aplicacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_pessoas", models.PositiveIntegerField()),
                ("homens", models.PositiveIntegerField()),
                ("mulheres", models.PositiveIntegerField()),
                ("jovens", models.PositiveIntegerField()),
                (
                    "atividade_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ieb.atividaderegistro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtividadeRegistroModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "Em desenvolvimento/proposto",
                                "Em desenvolvimento/proposto",
                            ),
                            ("Implementação ativa", "Implementação ativa"),
                            (
                                "Difundido (modelo adotado em outro lugar)",
                                "Difundido (modelo adotado em outro lugar)",
                            ),
                        ],
                        max_length=50,
                        verbose_name="Status do Modelo",
                    ),
                ),
                (
                    "atividade_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ieb.atividaderegistro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atividade Registro Modelo",
                "verbose_name_plural": "Atividades Registro Modelos",
            },
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("alinhamento_realizado", "Alinhamento Realizado"),
                            ("em_desenvolvimento", "Contrato em Desenvolvimento"),
                            ("assinado", "Contrato Assinado"),
                        ],
                        default="alinhamento_realizado",
                        max_length=30,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lei",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("tipo", models.CharField(choices=[("PGTA", "PGTA")], max_length=255)),
                (
                    "situacao",
                    models.CharField(
                        choices=[
                            ("em desenvolvimento", "Em Desenvolvimento"),
                            ("proposto", "Proposto"),
                            ("aprovado", "Aprovado"),
                            ("implementado", "Implementado"),
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeiHistorico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "situacao_anterior",
                    models.CharField(
                        choices=[
                            ("em desenvolvimento", "Em Desenvolvimento"),
                            ("proposto", "Proposto"),
                            ("aprovado", "Aprovado"),
                            ("implementado", "Implementado"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "situacao_nova",
                    models.CharField(
                        choices=[
                            ("em desenvolvimento", "Em Desenvolvimento"),
                            ("proposto", "Proposto"),
                            ("aprovado", "Aprovado"),
                            ("implementado", "Implementado"),
                        ],
                        max_length=255,
                    ),
                ),
                ("data_alteracao", models.DateTimeField(auto_now_add=True)),
                ("usuario", models.CharField(max_length=255)),
                (
                    "lei",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ieb.lei"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mobilizados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_mobilizado",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "tipo_apoio",
                    models.CharField(
                        choices=[
                            ("Contribuição em dinheiro", "Contribuição em dinheiro"),
                            ("Voluntariado", "Voluntariado"),
                            (
                                "Doação do tempo dos funcionários",
                                "Doação do tempo dos funcionários",
                            ),
                            (
                                "Doação de suprimentos, equipamentos",
                                "Doação de suprimentos, equipamentos",
                            ),
                            ("Propriedade intelectual", "Propriedade intelectual"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "fonte_apoio",
                    models.CharField(
                        choices=[
                            (
                                "Renda proveniente da atividades/projeto",
                                "Renda proveniente da atividades/projeto",
                            ),
                            ("Empresas", "Empresas"),
                            ("Fundação privada", "Fundação privada"),
                            (
                                "Outros doadores (incluindo multilaterais)",
                                "Outros doadores (incluindo multilaterais)",
                            ),
                            (
                                "Outras organizações sem fins lucrativos",
                                "Outras organizações sem fins lucrativos",
                            ),
                            (
                                "Indivíduo de alta renda/Investidor anjo",
                                "Indivíduo de alta renda/Investidor anjo",
                            ),
                            ("OUTRO (especifique)", "OUTRO (especifique)"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "atividade_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ieb.atividaderegistro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mobilizado",
                "verbose_name_plural": "Mobilizados",
            },
        ),
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Modelo",
                "verbose_name_plural": "Modelos",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="areageraltis",
            name="areageral",
        ),
        migrations.RemoveField(
            model_name="areageraltis",
            name="tis",
        ),
        migrations.RemoveField(
            model_name="modelos",
            name="atividade_registro",
        ),
        migrations.AlterModelOptions(
            name="arearestrito",
            options={
                "verbose_name": "Área Restrita",
                "verbose_name_plural": "Áreas Restritas",
            },
        ),
        migrations.RemoveField(
            model_name="areadireto",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="areageral",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="areageral",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="arearestrito",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="arearestrito",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="arearestrito",
            name="tis",
        ),
        migrations.RemoveField(
            model_name="contratos",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="contratos",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="contratos",
            name="tis",
        ),
        migrations.RemoveField(
            model_name="leis",
            name="adotado",
        ),
        migrations.RemoveField(
            model_name="leis",
            name="desenvolvimento",
        ),
        migrations.RemoveField(
            model_name="leis",
            name="implementado",
        ),
        migrations.RemoveField(
            model_name="leis",
            name="proposto",
        ),
        migrations.RemoveField(
            model_name="produtos",
            name="nome",
        ),
        migrations.RemoveField(
            model_name="produtos",
            name="tipo",
        ),
        migrations.RemoveField(
            model_name="produtos",
            name="tis",
        ),
        migrations.RemoveField(
            model_name="tis",
            name="cr_id",
        ),
        migrations.RemoveField(
            model_name="tis",
            name="dsei_id",
        ),
        migrations.RemoveField(
            model_name="tis",
            name="oilocal",
        ),
        migrations.AddField(
            model_name="areadireto",
            name="total_area",
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name="areadireto",
            name="total_tis",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="areageral",
            name="total_area",
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name="areageral",
            name="total_tis",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="arearestrito",
            name="area_em_ha",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="arearestrito",
            name="ti",
            field=models.ForeignKey(
                default=0.0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="area_restrito",
                to="ieb.tis",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="capacitados",
            name="foco_capacitacao",
            field=models.CharField(
                choices=[
                    (
                        "implementacao",
                        "Implementação melhorada/monitoramento/vigilância",
                    ),
                    (
                        "ativ_prod",
                        "Meios de subsistência/cadeia de valor sustentáveis melhorados",
                    ),
                    (
                        "governanca",
                        "Fortalecimento institucional/capacitação organizacional/governança",
                    ),
                ],
                default=0.0,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produtos",
            name="total_produtos",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="areadireto",
            name="atividade_registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ieb.atividaderegistro"
            ),
        ),
        migrations.RemoveField(
            model_name="areadireto",
            name="tis",
        ),
        migrations.AlterField(
            model_name="areageral",
            name="atividade_registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ieb.atividaderegistro"
            ),
        ),
        migrations.RemoveField(
            model_name="areageral",
            name="tis",
        ),
        migrations.AlterField(
            model_name="arearestrito",
            name="atividade_registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ieb.atividaderegistro"
            ),
        ),
        migrations.AlterField(
            model_name="contratos",
            name="atividade_registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ieb.atividaderegistro"
            ),
        ),
        migrations.AlterField(
            model_name="leis",
            name="atividade_registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ieb.atividaderegistro"
            ),
        ),
        migrations.AlterField(
            model_name="leis",
            name="total_leis",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.DeleteModel(
            name="AreaDiretoTIs",
        ),
        migrations.DeleteModel(
            name="AreaGeralTIs",
        ),
        migrations.DeleteModel(
            name="Modelos",
        ),
        migrations.AddField(
            model_name="contrato",
            name="produtos",
            field=models.ManyToManyField(related_name="contratos", to="ieb.produto"),
        ),
        migrations.AddField(
            model_name="atividaderegistromodelo",
            name="modelo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ieb.modelo"
            ),
        ),
        migrations.AddField(
            model_name="contratos",
            name="contratos",
            field=models.ManyToManyField(
                related_name="contratos_registro", to="ieb.contrato"
            ),
        ),
        migrations.AddField(
            model_name="leis",
            name="leis",
            field=models.ManyToManyField(related_name="leis", to="ieb.lei"),
        ),
        migrations.AddField(
            model_name="produtos",
            name="produtos",
            field=models.ManyToManyField(related_name="produtos", to="ieb.produto"),
        ),
        migrations.AddField(
            model_name="areadireto",
            name="tis",
            field=models.ManyToManyField(related_name="area_direto", to="ieb.tis"),
        ),
        migrations.AddField(
            model_name="areageral",
            name="tis",
            field=models.ManyToManyField(related_name="area_geral", to="ieb.tis"),
        ),
    ]
