# Generated by Django 4.2.9 on 2024-11-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0015_aplicacao_atividaderegistromodelo_contrato_lei_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividaderegistro",
            name="fotos_thumbnail",
            field=models.ImageField(
                blank=True, editable=False, upload_to="fotos/thumbnails/"
            ),
        ),
    ]
