# Generated by Django 4.2.9 on 2024-11-18 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0016_atividaderegistro_fotos_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividaderegistro",
            name="email_organizacao",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
