# Generated by Django 4.2.9 on 2026-03-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0017_atividaderegistro_email_organizacao"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaTematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Área Temática",
                "verbose_name_plural": "Áreas Temáticas",
            },
        ),
        migrations.AddField(
            model_name="indicador",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("area_restrito", "Área Restrita"),
                    ("area_direto", "Área Direta"),
                    ("area_geral", "Área Geral"),
                    ("treinados", "Pessoas Treinadas"),
                    ("leis_politicas", "Leis e Políticas"),
                    ("capacitados", "Organizações Capacitadas"),
                    ("aplicacao", "Aplicação"),
                    ("planos", "Planos"),
                    ("parcerias", "Parcerias"),
                    ("mobilizados", "Recursos Mobilizados"),
                    ("produtos", "Produtos"),
                    ("contratos", "Contratos"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProjetoIndicador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projeto_indicadores",
                        to="ieb.indicador",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projeto_indicadores",
                        to="ieb.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador do Projeto",
                "verbose_name_plural": "Indicadores do Projeto",
                "unique_together": {("projeto", "indicador")},
            },
        ),
        migrations.CreateModel(
            name="AtividadeTI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tis",
                        to="ieb.atividade",
                    ),
                ),
                (
                    "ti",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="ieb.tis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Terra Indígena da Atividade",
                "verbose_name_plural": "Terras Indígenas das Atividades",
                "unique_together": {("atividade", "ti")},
            },
        ),
        migrations.CreateModel(
            name="AtividadeOIRegional",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ois_regionais",
                        to="ieb.atividade",
                    ),
                ),
                (
                    "oiregional",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="ieb.oisregional",
                    ),
                ),
            ],
            options={
                "verbose_name": "OI Regional da Atividade",
                "verbose_name_plural": "OIs Regionais das Atividades",
                "unique_together": {("atividade", "oiregional")},
            },
        ),
        migrations.CreateModel(
            name="AtividadeOILocal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ois_locais",
                        to="ieb.atividade",
                    ),
                ),
                (
                    "oilocal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="ieb.oislocal",
                    ),
                ),
            ],
            options={
                "verbose_name": "OI Local da Atividade",
                "verbose_name_plural": "OIs Locais das Atividades",
                "unique_together": {("atividade", "oilocal")},
            },
        ),
        migrations.CreateModel(
            name="AtividadeAreaTematica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area_tematica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atividades",
                        to="ieb.areatematica",
                    ),
                ),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="areas_tematicas",
                        to="ieb.atividade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Área Temática da Atividade",
                "verbose_name_plural": "Áreas Temáticas das Atividades",
                "unique_together": {("atividade", "area_tematica")},
            },
        ),
    ]
