# Generated by Django 4.2.9 on 2026-03-09 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0018_areatematica_indicador_tipo_projetoindicador_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subatividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(max_length=255)),
                ("descricao", models.CharField(max_length=255)),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subatividades",
                        to="ieb.atividade",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="atividaderegistro",
            name="subatividade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ieb.subatividade",
            ),
        ),
    ]
