# Generated by Django 4.2.9 on 2026-03-09 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0019_subatividade_atividaderegistro_subatividade"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtividadeRegistroListaPresenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arquivo", models.FileField(upload_to="listas_presenca/")),
                (
                    "atividade_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_presenca_set",
                        to="ieb.atividaderegistro",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AtividadeRegistroFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("foto", models.ImageField(upload_to="fotos/")),
                (
                    "foto_thumbnail",
                    models.ImageField(
                        blank=True, editable=False, upload_to="fotos/thumbnails/"
                    ),
                ),
                (
                    "atividade_registro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos_set",
                        to="ieb.atividaderegistro",
                    ),
                ),
            ],
        ),
    ]
