# Generated by Django 4.2.9 on 2026-03-09 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0020_atividaderegistrolistapresenca_atividaderegistrofoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividaderegistrofoto",
            name="foto",
            field=models.ImageField(max_length=255, upload_to="fotos/"),
        ),
        migrations.AlterField(
            model_name="atividaderegistrofoto",
            name="foto_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                max_length=255,
                upload_to="fotos/thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="atividaderegistrolistapresenca",
            name="arquivo",
            field=models.FileField(max_length=255, upload_to="listas_presenca/"),
        ),
    ]
