# Generated by Django 4.2.9 on 2026-03-11 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0021_fix_imagefield_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Programa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("sigla", models.CharField(max_length=50, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Programa",
                "verbose_name_plural": "Programas",
                "ordering": ["sigla"],
            },
        ),
        migrations.AddField(
            model_name="projeto",
            name="financiadores",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos",
                to="ieb.financiador",
                verbose_name="Financiadores",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="projeto_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subprojetos",
                to="ieb.projeto",
                verbose_name="Projeto pai",
            ),
        ),
        migrations.AddField(
            model_name="projeto",
            name="programas",
            field=models.ManyToManyField(
                blank=True,
                related_name="projetos",
                to="ieb.programa",
                verbose_name="Programas",
            ),
        ),
    ]
