# Generated by Django 4.2.9 on 2026-03-12 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0026_planos_redesign"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicadorFinanciador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("codigo", models.CharField(blank=True, max_length=255)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("reporte", models.CharField(blank=True, max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("area_restrito", "Área Restrita"),
                            ("area_direto", "Área Direta"),
                            ("area_geral", "Área Geral"),
                            ("treinados", "Pessoas Treinadas"),
                            ("leis_politicas", "Leis e Políticas"),
                            ("capacitados", "Organizações Capacitadas"),
                            ("aplicacao", "Aplicação"),
                            ("planos", "Planos"),
                            ("parcerias", "Parcerias"),
                            ("mobilizados", "Recursos Mobilizados"),
                            ("produtos", "Produtos"),
                            ("contratos", "Contratos"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=30,
                    ),
                ),
                (
                    "financiador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="indicadores_proprios",
                        to="ieb.financiador",
                        verbose_name="Financiador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador de Financiador",
                "verbose_name_plural": "Indicadores de Financiadores",
            },
        ),
        migrations.AlterField(
            model_name="planos",
            name="atividade_registro",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ieb.atividaderegistro"
            ),
        ),
        migrations.CreateModel(
            name="MetaFinanciador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base", models.FloatField()),
                ("meta", models.FloatField()),
                ("data", models.DateField()),
                (
                    "atividade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas_financiador",
                        to="ieb.atividade",
                    ),
                ),
                (
                    "indicador_financiador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas",
                        to="ieb.indicadorfinanciador",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aplicacao",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="areadireto",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="areageral",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="arearestrito",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="capacitados",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="contratos",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="leis",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="mobilizados",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="parcerias",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="produtos",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddField(
            model_name="treinados",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.CreateModel(
            name="ProjetoIndicadorFin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "indicador_financiador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projeto_indicadores_fin",
                        to="ieb.indicadorfinanciador",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projeto_indicadores_fin",
                        to="ieb.projeto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador de Financiador do Projeto",
                "verbose_name_plural": "Indicadores de Financiadores do Projeto",
                "unique_together": {("projeto", "indicador_financiador")},
            },
        ),
    ]
