# Generated by Django 4.2.9 on 2026-03-30 19:22

from django.db import migrations, models


def rename_tipos(apps, schema_editor):
    Indicador = apps.get_model('ieb', 'Indicador')
    IndicadorFinanciador = apps.get_model('ieb', 'IndicadorFinanciador')
    for Model in (Indicador, IndicadorFinanciador):
        Model.objects.filter(tipo='treinados').update(tipo='pessoas')
        Model.objects.filter(tipo='capacitados').update(tipo='organizacoes')
        Model.objects.filter(tipo='aplicacao').update(tipo='pessoas')
        Model.objects.filter(tipo__in=['area_restrito', 'area_direto', 'area_geral']).update(tipo='area')


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0028_planos_plano_fk"),
    ]

    operations = [
        migrations.RunPython(rename_tipos, migrations.RunPython.noop),

        migrations.AlterField(
            model_name="indicador",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pessoas", "Pessoas"),
                    ("organizacoes", "Organizações"),
                    ("area", "Área"),
                    ("areas_protegidas", "Áreas Protegidas"),
                    ("eventos", "Eventos"),
                    ("planos", "Planos"),
                    ("parcerias", "Parcerias"),
                    ("mobilizados", "Recursos Mobilizados"),
                    ("produtos", "Produtos"),
                    ("contratos", "Contratos"),
                    ("redes", "Redes"),
                    ("pequenos_projetos", "Pequenos Projetos"),
                    ("fundos", "Fundos"),
                    ("leis_politicas", "Leis e Políticas"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="indicadorfinanciador",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("pessoas", "Pessoas"),
                    ("organizacoes", "Organizações"),
                    ("area", "Área"),
                    ("areas_protegidas", "Áreas Protegidas"),
                    ("eventos", "Eventos"),
                    ("planos", "Planos"),
                    ("parcerias", "Parcerias"),
                    ("mobilizados", "Recursos Mobilizados"),
                    ("produtos", "Produtos"),
                    ("contratos", "Contratos"),
                    ("redes", "Redes"),
                    ("pequenos_projetos", "Pequenos Projetos"),
                    ("fundos", "Fundos"),
                    ("leis_politicas", "Leis e Políticas"),
                    ("outro", "Outro"),
                ],
                default="outro",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="plano",
            name="situacao",
            field=models.CharField(
                choices=[
                    ("em desenvolvimento", "Em Desenvolvimento"),
                    ("proposto", "Proposto"),
                    ("adotado", "Adotado"),
                    ("em implementacao", "Em Implementação"),
                    ("implementado", "Implementado"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="plano",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PGTA", "PGTA"),
                    ("Plano de Adaptação", "Plano de Adaptação"),
                    ("Plano de Manejo", "Plano de Manejo"),
                    ("Plano de Enfrentamento", "Plano de Enfrentamento"),
                    ("Plano de Diagnóstico", "Plano de Diagnóstico"),
                    ("Outro", "Outro"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="planohistorico",
            name="situacao_anterior",
            field=models.CharField(
                choices=[
                    ("em desenvolvimento", "Em Desenvolvimento"),
                    ("proposto", "Proposto"),
                    ("adotado", "Adotado"),
                    ("em implementacao", "Em Implementação"),
                    ("implementado", "Implementado"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="planohistorico",
            name="situacao_nova",
            field=models.CharField(
                choices=[
                    ("em desenvolvimento", "Em Desenvolvimento"),
                    ("proposto", "Proposto"),
                    ("adotado", "Adotado"),
                    ("em implementacao", "Em Implementação"),
                    ("implementado", "Implementado"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="planos",
            name="situacao_anterior",
            field=models.CharField(
                blank=True,
                choices=[
                    ("em desenvolvimento", "Em Desenvolvimento"),
                    ("proposto", "Proposto"),
                    ("adotado", "Adotado"),
                    ("em implementacao", "Em Implementação"),
                    ("implementado", "Implementado"),
                ],
                editable=False,
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="planos",
            name="situacao_nova",
            field=models.CharField(
                choices=[
                    ("em desenvolvimento", "Em Desenvolvimento"),
                    ("proposto", "Proposto"),
                    ("adotado", "Adotado"),
                    ("em implementacao", "Em Implementação"),
                    ("implementado", "Implementado"),
                ],
                default="em desenvolvimento",
                max_length=255,
            ),
        ),
    ]
