# Generated by Django 4.2.9 on 2026-03-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0029_tipo_choices_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="indicador",
            name="desag_direto",
            field=models.BooleanField(
                default=False, verbose_name="Área Direta (M2M → soma HA)"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_encontros",
            field=models.BooleanField(default=False, verbose_name="Encontros"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_formacoes",
            field=models.BooleanField(default=False, verbose_name="Formações"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_homens",
            field=models.BooleanField(default=False, verbose_name="Homens"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_indireto",
            field=models.BooleanField(
                default=False, verbose_name="Área Indireta (M2M → soma HA)"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_jovens",
            field=models.BooleanField(default=False, verbose_name="Jovens"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_mulheres",
            field=models.BooleanField(default=False, verbose_name="Mulheres"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_org_extrativistas",
            field=models.BooleanField(default=False, verbose_name="Org. Extrativistas"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_org_indigenas",
            field=models.BooleanField(default=False, verbose_name="Org. Indígenas"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_org_sc",
            field=models.BooleanField(default=False, verbose_name="Sociedade Civil"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_pa",
            field=models.BooleanField(
                default=False, verbose_name="Projeto de Assentamento (PA)"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_participantes",
            field=models.BooleanField(
                default=False, verbose_name="Registrar participantes"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_pct",
            field=models.BooleanField(default=False, verbose_name="PCT (grupo)"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_pct_extrativistas",
            field=models.BooleanField(
                default=False, verbose_name="PCT — Extrativistas"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_pct_indigenas",
            field=models.BooleanField(default=False, verbose_name="PCT — Indígenas"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_pct_quilombolas",
            field=models.BooleanField(default=False, verbose_name="PCT — Quilombolas"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_restrito",
            field=models.BooleanField(
                default=False, verbose_name="Área Restrita (HA manual)"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_reunioes",
            field=models.BooleanField(default=False, verbose_name="Reuniões"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_seminarios",
            field=models.BooleanField(default=False, verbose_name="Seminários"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_servidor_publico",
            field=models.BooleanField(default=False, verbose_name="Servidor Público"),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_ti",
            field=models.BooleanField(
                default=False, verbose_name="Terra Indígena (TI)"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_tuc",
            field=models.BooleanField(
                default=False, verbose_name="Território de Uso Comum (TUC)"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_uc",
            field=models.BooleanField(
                default=False, verbose_name="Unidade de Conservação (UC)"
            ),
        ),
        migrations.AddField(
            model_name="indicador",
            name="tem_foco",
            field=models.BooleanField(
                default=False, verbose_name="Coletar foco da ação"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_direto",
            field=models.BooleanField(
                default=False, verbose_name="Área Direta (M2M → soma HA)"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_encontros",
            field=models.BooleanField(default=False, verbose_name="Encontros"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_formacoes",
            field=models.BooleanField(default=False, verbose_name="Formações"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_homens",
            field=models.BooleanField(default=False, verbose_name="Homens"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_indireto",
            field=models.BooleanField(
                default=False, verbose_name="Área Indireta (M2M → soma HA)"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_jovens",
            field=models.BooleanField(default=False, verbose_name="Jovens"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_mulheres",
            field=models.BooleanField(default=False, verbose_name="Mulheres"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_org_extrativistas",
            field=models.BooleanField(default=False, verbose_name="Org. Extrativistas"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_org_indigenas",
            field=models.BooleanField(default=False, verbose_name="Org. Indígenas"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_org_sc",
            field=models.BooleanField(default=False, verbose_name="Sociedade Civil"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_pa",
            field=models.BooleanField(
                default=False, verbose_name="Projeto de Assentamento (PA)"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_participantes",
            field=models.BooleanField(
                default=False, verbose_name="Registrar participantes"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_pct",
            field=models.BooleanField(default=False, verbose_name="PCT (grupo)"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_pct_extrativistas",
            field=models.BooleanField(
                default=False, verbose_name="PCT — Extrativistas"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_pct_indigenas",
            field=models.BooleanField(default=False, verbose_name="PCT — Indígenas"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_pct_quilombolas",
            field=models.BooleanField(default=False, verbose_name="PCT — Quilombolas"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_restrito",
            field=models.BooleanField(
                default=False, verbose_name="Área Restrita (HA manual)"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_reunioes",
            field=models.BooleanField(default=False, verbose_name="Reuniões"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_seminarios",
            field=models.BooleanField(default=False, verbose_name="Seminários"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_servidor_publico",
            field=models.BooleanField(default=False, verbose_name="Servidor Público"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_ti",
            field=models.BooleanField(
                default=False, verbose_name="Terra Indígena (TI)"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_tuc",
            field=models.BooleanField(
                default=False, verbose_name="Território de Uso Comum (TUC)"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_uc",
            field=models.BooleanField(
                default=False, verbose_name="Unidade de Conservação (UC)"
            ),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="tem_foco",
            field=models.BooleanField(
                default=False, verbose_name="Coletar foco da ação"
            ),
        ),
    ]
