# Generated by Django 4.2.9 on 2026-03-30 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0031_result_models_redesign"),
    ]

    operations = [
        migrations.AddField(
            model_name="meta",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Início do período de apuração"
            ),
        ),
        migrations.AddField(
            model_name="metafinanciador",
            name="data_inicio",
            field=models.DateField(
                blank=True, null=True, verbose_name="Início do período de apuração"
            ),
        ),
        migrations.AlterField(
            model_name="meta",
            name="data",
            field=models.DateField(verbose_name="Prazo / Fim do período"),
        ),
        migrations.AlterField(
            model_name="metafinanciador",
            name="data",
            field=models.DateField(verbose_name="Prazo / Fim do período"),
        ),
    ]
