# Generated by Django 4.2.9 on 2026-04-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0032_meta_periodo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contratos",
            name="valor_total",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=15
            ),
        ),
        migrations.AlterUniqueTogether(
            name="atividade",
            unique_together={("componente", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="componente",
            unique_together={("projeto", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="equipeprojeto",
            unique_together={("equipe", "projeto")},
        ),
        migrations.AlterUniqueTogether(
            name="oiregloc",
            unique_together={("oiregional", "oilocal")},
        ),
        migrations.AlterUniqueTogether(
            name="projetooi",
            unique_together={("oilocal", "projeto")},
        ),
        migrations.AlterUniqueTogether(
            name="projetoti",
            unique_together={("tis", "projeto")},
        ),
        migrations.AlterUniqueTogether(
            name="subatividade",
            unique_together={("atividade", "codigo")},
        ),
        migrations.AlterUniqueTogether(
            name="tisigati",
            unique_together={("igati", "tis")},
        ),
        migrations.AddConstraint(
            model_name="atividaderegistro",
            constraint=models.CheckConstraint(
                check=models.Q(("data_final__gte", models.F("data_inicio"))),
                name="data_final_gte_data_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="meta",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("data_inicio__isnull", True),
                    ("data__gte", models.F("data_inicio")),
                    _connector="OR",
                ),
                name="meta_data_gte_data_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="metafinanciador",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("data_inicio__isnull", True),
                    ("data__gte", models.F("data_inicio")),
                    _connector="OR",
                ),
                name="metafinanciador_data_gte_data_inicio",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilizados",
            constraint=models.CheckConstraint(
                check=models.Q(("valor_mobilizado__gt", 0)),
                name="valor_mobilizado_positive",
            ),
        ),
    ]
