# Generated by Django 4.2.9 on 2026-04-28 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0033_alter_contratos_valor_total_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="area",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="areasprotegidas",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="contratos",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="evento",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="leis",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="mobilizados",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="organizacoes",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="outro",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="parcerias",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="pessoas",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="produtos",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="indicador",
            name="desag_org_governo",
            field=models.BooleanField(default=False, verbose_name="Governo"),
        ),
        migrations.AddField(
            model_name="indicadorfinanciador",
            name="desag_org_governo",
            field=models.BooleanField(default=False, verbose_name="Governo"),
        ),
        migrations.AddField(
            model_name="organizacoes",
            name="org_governo",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Governo"
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="areasprotegidas",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="areasprotegidas",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="atividaderegistromodelo",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="contratos",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="contratos",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="fundo",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="fundo",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="leis",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="leis",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="mobilizados",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="mobilizados",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="organizacoes",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="organizacoes",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="outro",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="outro",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="parcerias",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="parcerias",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="pequenoprojeto",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="pequenoprojeto",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="pessoas",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="pessoas",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="planos",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="planos",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="produtos",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AlterField(
            model_name="rede",
            name="indicador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_set",
                to="ieb.indicador",
            ),
        ),
        migrations.AlterField(
            model_name="rede",
            name="indicador_financiador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_fin_set",
                to="ieb.indicadorfinanciador",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="area_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="area_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="area",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="area_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="areasprotegidas",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="areasprotegidas_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="areasprotegidas",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="areasprotegidas_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="areasprotegidas",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="areasprotegidas_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratos",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="contratos_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="contratos_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="contratos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="contratos_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="evento",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="evento_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="evento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="evento_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="evento",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="evento_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundo",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="fundo_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="fundo_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="fundo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="fundo_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="leis",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="leis_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="leis",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="leis_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="leis",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="leis_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilizados",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="mobilizados_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilizados",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="mobilizados_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="mobilizados",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="mobilizados_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizacoes",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="organizacoes_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizacoes",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="organizacoes_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizacoes",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="organizacoes_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizacoes",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("org_sociedade_civil__lte", models.F("total_organizacoes")),
                    ("org_sociedade_civil__isnull", True),
                    _connector="OR",
                ),
                name="org_sc_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizacoes",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("org_indigenas__lte", models.F("total_organizacoes")),
                    ("org_indigenas__isnull", True),
                    _connector="OR",
                ),
                name="org_indigenas_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizacoes",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("org_extrativistas__lte", models.F("total_organizacoes")),
                    ("org_extrativistas__isnull", True),
                    _connector="OR",
                ),
                name="org_extrativistas_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="organizacoes",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("org_governo__lte", models.F("total_organizacoes")),
                    ("org_governo__isnull", True),
                    _connector="OR",
                ),
                name="org_governo_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="outro",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="outro_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="outro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="outro_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="outro",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="outro_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcerias",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="parcerias_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcerias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="parcerias_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcerias",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="parcerias_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="pequenoprojeto",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="pequenoprojeto_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="pequenoprojeto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="pequenoprojeto_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="pequenoprojeto",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="pequenoprojeto_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="pessoas",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="pessoas_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="pessoas",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="pessoas_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="pessoas",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="pessoas_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="pessoas",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("homens__lte", models.F("total_pessoas")),
                    ("homens__isnull", True),
                    _connector="OR",
                ),
                name="pessoas_homens_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="pessoas",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("mulheres__lte", models.F("total_pessoas")),
                    ("mulheres__isnull", True),
                    _connector="OR",
                ),
                name="pessoas_mulheres_lte_total",
            ),
        ),
        migrations.AddConstraint(
            model_name="planos",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="planos_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="planos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="planos_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="planos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="planos_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtos",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="produtos_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="produtos_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="produtos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="produtos_unique_ind_fin",
            ),
        ),
        migrations.AddConstraint(
            model_name="rede",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("indicador__isnull", False),
                    ("indicador_financiador__isnull", False),
                    _negated=True,
                ),
                name="rede_single_fk",
            ),
        ),
        migrations.AddConstraint(
            model_name="rede",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador__isnull", False)),
                fields=("atividade_registro", "indicador"),
                name="rede_unique_indicador",
            ),
        ),
        migrations.AddConstraint(
            model_name="rede",
            constraint=models.UniqueConstraint(
                condition=models.Q(("indicador_financiador__isnull", False)),
                fields=("atividade_registro", "indicador_financiador"),
                name="rede_unique_ind_fin",
            ),
        ),
    ]
