# Generated by Forge on 2026-04-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def convert_usuario_to_fk(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    LeiHistorico = apps.get_model('ieb', 'LeiHistorico')
    PlanoHistorico = apps.get_model('ieb', 'PlanoHistorico')

    for Model in (LeiHistorico, PlanoHistorico):
        for obj in Model.objects.all().only('pk', 'usuario'):
            raw_usuario = obj.usuario
            username = str(raw_usuario).strip() if raw_usuario else ''
            if username.isdigit():
                continue
            user = User.objects.filter(username=username).first() if username else None
            Model.objects.filter(pk=obj.pk).update(usuario=str(user.pk) if user else None)


def convert_usuario_to_string(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL.split('.')[0], settings.AUTH_USER_MODEL.split('.')[1])
    LeiHistorico = apps.get_model('ieb', 'LeiHistorico')
    PlanoHistorico = apps.get_model('ieb', 'PlanoHistorico')

    for Model in (LeiHistorico, PlanoHistorico):
        for obj in Model.objects.all().only('pk', 'usuario'):
            raw_usuario = obj.usuario
            user = User.objects.filter(pk=raw_usuario).first() if raw_usuario else None
            Model.objects.filter(pk=obj.pk).update(usuario=user.username if user else '')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ieb', '0034_alter_area_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicadorfinanciador',
            name='equivalente_ieb',
            field=models.ForeignKey(
                blank=True,
                help_text='Quando preenchido, os resultados deste indicador de financiador sao contabilizados tambem no indicador IEB equivalente.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='ieb.indicador',
                verbose_name='Indicador IEB equivalente',
            ),
        ),
        migrations.AlterField(
            model_name='indicador',
            name='tipo',
            field=models.CharField(choices=[('pessoas', 'Pessoas'), ('organizacoes', 'Organizações'), ('area', 'Área'), ('areas_protegidas', 'Áreas Protegidas'), ('eventos', 'Eventos'), ('planos', 'Planos'), ('parcerias', 'Parcerias'), ('mobilizados', 'Recursos Mobilizados'), ('produtos', 'Produtos'), ('contratos', 'Contratos'), ('redes', 'Redes'), ('pequenos_projetos', 'Pequenos Projetos'), ('fundos', 'Fundos'), ('leis_politicas', 'Leis e Políticas')], default='pessoas', max_length=30),
        ),
        migrations.AlterField(
            model_name='indicadorfinanciador',
            name='tipo',
            field=models.CharField(choices=[('pessoas', 'Pessoas'), ('organizacoes', 'Organizações'), ('area', 'Área'), ('areas_protegidas', 'Áreas Protegidas'), ('eventos', 'Eventos'), ('planos', 'Planos'), ('parcerias', 'Parcerias'), ('mobilizados', 'Recursos Mobilizados'), ('produtos', 'Produtos'), ('contratos', 'Contratos'), ('redes', 'Redes'), ('pequenos_projetos', 'Pequenos Projetos'), ('fundos', 'Fundos'), ('leis_politicas', 'Leis e Políticas')], default='pessoas', max_length=30),
        ),
        migrations.RunPython(convert_usuario_to_fk, convert_usuario_to_string),
        migrations.AlterField(
            model_name='leihistorico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='planohistorico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.RunSQL(
            "UPDATE ieb_pequenoprojeto SET valor_total = 0 WHERE valor_total IS NULL",
            migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            "UPDATE ieb_fundo SET valor_total = 0 WHERE valor_total IS NULL",
            migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='pequenoprojeto',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='fundo',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddConstraint(
            model_name='pequenoprojeto',
            constraint=models.CheckConstraint(check=models.Q(('quantidade__gte', 1)), name='pequenoprojeto_quantidade_min_1'),
        ),
        migrations.AddConstraint(
            model_name='fundo',
            constraint=models.CheckConstraint(check=models.Q(('quantidade__gte', 1)), name='fundo_quantidade_min_1'),
        ),
        migrations.DeleteModel(
            name='Outro',
        ),
        migrations.AddField(
            model_name='atividaderegistromodelo',
            name='indicador_financiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_fin_set', to='ieb.indicadorfinanciador'),
        ),
        migrations.AddConstraint(
            model_name='atividaderegistromodelo',
            constraint=models.CheckConstraint(check=models.Q(('indicador__isnull', False), ('indicador_financiador__isnull', False), _negated=True), name='atividaderegistromodelo_single_fk'),
        ),
        migrations.AddConstraint(
            model_name='atividaderegistromodelo',
            constraint=models.UniqueConstraint(condition=models.Q(('indicador__isnull', False)), fields=('atividade_registro', 'indicador'), name='atividaderegistromodelo_unique_indicador'),
        ),
        migrations.AddConstraint(
            model_name='atividaderegistromodelo',
            constraint=models.UniqueConstraint(condition=models.Q(('indicador_financiador__isnull', False)), fields=('atividade_registro', 'indicador_financiador'), name='atividaderegistromodelo_unique_ind_fin'),
        ),
    ]
