# Generated by Django 4.2.9 on 2026-04-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0035_onda4_coerencia_dominio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizacoes",
            name="foco",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soc_civil", "Fortalecimento da sociedade civil"),
                    ("gov_territorial", "Governança Territorial e Ambiental"),
                    ("defesa_direitos", "Defesa de Direitos"),
                    ("sociobiodiversidade", "Economias da Sociobiodiversidade"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="pessoas",
            name="foco",
            field=models.CharField(
                blank=True,
                choices=[
                    ("soc_civil", "Fortalecimento da sociedade civil"),
                    ("gov_territorial", "Governança Territorial e Ambiental"),
                    ("defesa_direitos", "Defesa de Direitos"),
                    ("sociobiodiversidade", "Economias da Sociobiodiversidade"),
                ],
                max_length=20,
            ),
        ),
    ]
