# Generated by Django 4.2.9 on 2026-04-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0036_foco_choices_danida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planos",
            name="situacao_nova",
            field=models.CharField(
                blank=True,
                choices=[
                    ("em desenvolvimento", "Em Desenvolvimento"),
                    ("proposto", "Proposto"),
                    ("adotado", "Adotado"),
                    ("em implementacao", "Em Implementação"),
                    ("implementado", "Implementado"),
                ],
                default="",
                max_length=255,
            ),
        ),
    ]
