# Generated by Django 4.2.9 on 2026-04-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ieb", "0037_planos_simplificar_situacao_nova"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fundo",
            name="fundo_quantidade_min_1",
        ),
        migrations.AlterField(
            model_name="fundo",
            name="quantidade",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
