# Register your models here.
from django.contrib import admin

# Register your models here.
from .models import *

admin.site.register(OIsRegional)
admin.site.register(Financiador)
admin.site.register(Projeto)
admin.site.register(Instituicao)
admin.site.register(Componente)
admin.site.register(Atividade)
admin.site.register(OIsLocal)
admin.site.register(TIs)
admin.site.register(Aldeia)
admin.site.register(Indigena)
admin.site.register(Equipe)
admin.site.register(EquipeProjeto)
admin.site.register(Indicador)
admin.site.register(Meta)
admin.site.register(AtividadeRegistro)
admin.site.register(ProjetoOI)
admin.site.register(ProjetoTI)
admin.site.register(OIRegLoc)
admin.site.register(AtividadeRegistroEquipe)
admin.site.register(Treinados)
admin.site.register(Capacitados)
admin.site.register(FormacaoIndigena)
admin.site.register(Planos)
admin.site.register(Modelo)
admin.site.register(Parcerias)
admin.site.register(Produtos)
admin.site.register(Contratos)
admin.site.register(Leis)
admin.site.register(AreaRestrito)
admin.site.register(AreaDireto)
admin.site.register(AreaGeral)
admin.site.register(IGATI)
admin.site.register(TIsIGATI)
admin.site.register(CR)
admin.site.register(CTL)
admin.site.register(DSEI)
admin.site.register(Posto)
admin.site.register(Casai)
admin.site.register(Polo)
admin.site.register(AIS)
admin.site.register(Escola)
admin.site.register(Professores)
admin.site.register(Organizacao)
admin.site.register(Parceria)
admin.site.register(Plano)
admin.site.register(Produto)
admin.site.register(Contrato)
admin.site.register(Lei)
admin.site.register(Aplicacao)
admin.site.register(Mobilizados)